### ISSUE TITLE
The documentation for `elements_are` has unclear requirements

### ISSUE THREAD

**Issue by kupiakos** [google/googletest-rust#330]
I expected to be able to use `elements_are!` to be able to test that an iterator implementation is correct, but this isn't supported. The documentation says "The actual value must be a container implementing `IntoIterator`". This is incorrect - it's types where a shared borrow of the type is `IntoIterator`. The documentation should be more clear that it expects to work with a borrow. I expected to be able to test directly against a proxy type that represents a wrapped shared reference, but that itself is `IntoIterator` of shared references, not a reference to the proxy type (as that's essentially a double-reference).

If it didn't break consistency with the other matchers I would suggest this matcher consume its input for `IntoIterator`.

**Comment by kupiakos** [comment]
One possible design: if we add two new macros `iter_elements_are!` and `iter_unordered_elements_are!` that these two defer two, it could remain a non-breaking change and also allow direct testing of iterators.

**Comment by hovinen** [comment]
Hi Alyssa,

You're right -- the documentation is inaccurate on that point. I'll prepare a PR to improve it.

We had considered the idea of introducing a family of macros `verify_that_iter!`, `expect_that_iter!`, `assert_that_iter!` which would allow matching directly on iterators rather than having to collect them to collections first. That wouldn't be quite the same as `iter_elements_are!` as you propose -- one wouldn't be able to use it to match on iterators nested inside other data structures. But it would be easier to integrate into the existing matcher semantics. What do you think?

**Comment by kupiakos** [comment]
Thanks for fixing the docs!

> We had considered the idea of introducing a family of macros `verify_that_iter!`, `expect_that_iter!`, `assert_that_iter!` which would allow matching directly on iterators rather than having to collect them to collections first.

I suspect that would be much heavier weight and harder to understand for users? But I'm diving a bit more into the code and see why the way that `Matcher` is structured makes it particularly challenging to consume the `actual` part. Which is a bit frustrating considering pretty much all matchers will be constructed once and then work on a single input. It's still _possible_ with shenanigans like `ActualT = RefCell<Option<Iter>>` but then making `explain_match` still work after consuming the input would be even more cursed....it's just not designed for consuming the `actual` part.

> one wouldn't be able to use it to match on iterators nested inside other data structures

This is the API shape I was imagining:

```rust
let data = vec![vec![1,2].into_iter(), vec![10, 10].into_iter(), vec![3, 4, 5].into_iter()];
// Passes:
assert_that!(my_value.into_iter(), iter_elements_are![
    iter_elements_are![eq(1), eq(2)],
    iter_elements_are![each(10)],
    iter_elements_are![eq(3), eq(4), eq(5)]
]);
```

> But it would be easier to integrate into the existing matcher semantics.

The consistency seems particularly valuable there, but the primary issue is that usage of `Matcher::matches` expects that the `actual` arg won't be shared-mutated when you call it, so you can (paraphrased) `if matcher.matches(&actual).is_no_match() { eprintln!("match fail: {}", matcher.explain_match(&actual)) }`
