### ISSUE TITLE
Add support for custom formatted error messages in `*_that!`

### ISSUE THREAD

**Issue by kupiakos** [google/googletest-rust#331]
Example usage:

```rust
for n in 0..100 {
    let something = unimplemented!();
    assert_that!(test_fn(n), eq(something), "for {n}"):
}
```

**Comment by hovinen** [comment]
We do have [`failure_message`](https://docs.rs/googletest/latest/googletest/trait.GoogleTestSupport.html#tymethod.failure_message) and [`with_failure_message`](https://docs.rs/googletest/latest/googletest/trait.GoogleTestSupport.html#tymethod.with_failure_message) which allow:

```
verify_that!(test_fn(n), eq(something)).with_failure_message(|| format!("for {n}")).unwrap()
```

Does that work for you, or do you want a more abbreviated version integrated into `assert_that!` et al.?

**Comment by kupiakos** [comment]
A more abbreviated version in args after the matcher would be strongly preferred - in part to make migration from `assert_eq!` and kin much more trivial.
