### ISSUE TITLE
Implement `Clone` for possible matchers

### ISSUE THREAD

**Issue by kupiakos** [google/googletest-rust#355]
To simply reuse the same long matcher expression across multiple checks.

**Comment by bjacotg** [comment]
I run into temporary lifetime issue by taking the matcher by reference. However, in #356, I just made all `&impl Matcher` implement `Matcher` which seems to fix both issues.

**Comment by kupiakos** [comment]
@bjacotg Implementing `Clone` might still be useful for other reasons, but matching on `&Matcher` works just as well for me!
