### ISSUE TITLE
Learning resource

### ISSUE THREAD

**Issue by LukeMathWalker** [google/googletest-rust#376]
Mainmatter has released its [advanced testing workshop material](https://github.com/mainmatter/rust-advanced-testing-workshop/), licensed as CC BY-NC 4.0 Deed. It is structured as a self-paced learning course and the first section [covers `googletest` and its matchers quite extensively](https://github.com/mainmatter/rust-advanced-testing-workshop/tree/main/exercises/01_better_assertions).

Would you be interested in linking to it as a learning resource, either in the README or in the documentation of `googletest`?

**Comment by mgeisler** [comment]
Hey @LukeMathWalker, I think that is a great idea!

When you're at it, please also add a link to the [GoogleTest](https://google.github.io/comprehensive-rust/android/testing/googletest.html) section of Comprehensive Rust.

Also, I would be happy to link your workshops from [Other Resources](https://google.github.io/comprehensive-rust/other-resources.html) in Comprehensive Rust.
