### ISSUE TITLE
Implementing custom matcher against non-Copy item

### ISSUE THREAD

**Issue by vegardgs-ksat** [google/googletest-rust#534]
I wanted to implement a `json_subset_of` matcher comparing an actual `serde_json::Value` against my own. However, with the updated `Matcher` trait now requiring the `<ActualT: Debug + Copy>`, I cannot find a way to achieve my impl.

Here is a rough draft if my thought process:
```rust
use googletest::{
    description::Description,
    matcher::{Matcher, MatcherBase, MatcherResult},
};

#[derive(MatcherBase)]
struct JsonSubsetMatcher {
    expected: serde_json::Value,
}

impl Matcher<serde_json::Value> for JsonSubsetMatcher {
    fn matches(&self, actual: serde_json::Value) -> MatcherResult {
        todo!()
    }

    fn describe(&self, matcher_result: MatcherResult) -> Description {
        todo!()
    }
}

#[test]
fn compare_test() {
    let actual = serde_json::json!({
        "code": "METHOD_UNSUPPORTED",
        "message": "This method is not supported"
    });
    let compare = serde_json::json!({
        "code": "METHOD_UNSUPPORTED"
    });

    assert_that!(actual, json_subset_of(compare));
}
```

Is this not achievable with the new Matcher design, or am I missing something?

**Comment by bjacotg** [comment]
The way to solve this is to `impl Matcher<&serde_json::Value>` instead of `impl Matcher<serde_json::Value>`.

Note that `assert_that!` is smart enough to take a reference of `actual`, hence `assert_that!(actual, json_subset_of(compare))` will still compile even without an extra `&`.

**Comment by vegardgs-ksat** [comment]
Its so painfully obvious when you know, you know.

I was browsing through the documentation in an attempt to find hints at this, but found none. Maybe a short sentence or section about implementing it on references for non-copy type can aid future confusions - either on the trait definition docs, or the `Writing matchers` section at the root.

Thanks alot for the info!
