### ISSUE TITLE
Testing with sqlx::test fixtures

### ISSUE THREAD

**Issue by adanielnoel** [google/googletest-rust#547]
The `sqlx::test` attribute macro creates an isolated database per test and provides it as a fixture. Googletest complains that fixtures are not supported in async tests.

Minimal example:

```rs
use googletest::prelude::*;
use sqlx::PgPool;

#[gtest]
#[sqlx::test]
async fn test_create_organization_success(pool: PgPool) {
    assert_that!(pool.is_closed(), is_false());
}
```

```
error: Googletest does not currently support fixture with async. Consider using rstest
  --> src/bin/scratch.rs:10:1
   |
10 | async fn test_create_organization_success(pool: PgPool) {
   | ^^^^^
```

Is there a timeline for this feature?

Would `rstest` help here somehow?

**Comment by bjacotg** [comment]
This is a known gap, but supporting fixtures in async test has not been prioritized yet. I am happy to review a PR though!

`rstest` support fixtures (with a slightly different semantic as `gtest`) in async test but this may clash as well with `#[sqlx::test]`. There may be a way to avoid those issues if you order `#[gtest]` `#[rstest]` and `#[sqlx::test]` in the right order but it is brittle.

Do you need non-fatal expectations (`expect_that!` and friends)? If not, you may just remove `#[gtest]` and only rely on `assert_that!` and `verify_that!` while waiting the full support of fixtures in async tests.

**Comment by adanielnoel** [comment]
Non-fatal exceptions are a nice to have but not what I need at the moment, so it seems I can start adopting the crate :)

I'm relatively new to Rust but if I get down the path of supporting fixtures I'll send a PR.

Thanks for the help!
